### ISSUE TITLE
Enrich not working with new 1.0.2 version

### ISSUE THREAD

**Issue by raffsokolowski** [pm4net/serilog-enrichers-callerinfo#2]
Hi,

I've updated to ver 1.0.2 and the enricher is no longer working.

i'm using .net core 7 and configuring the enricher in program.cs like:

.Enrich.WithCallerInfo(includeFileInfo: false, assemblyPrefix: "MyAssemblyName.")

When I downgrade back to 1.0.1 it works perfectly without any changes to the above code.

Regards
Raff

**Comment by johannesmols** [comment]
Hi @raffsokolowski, I have slightly changed how the assemblies are discovered in response to #1.
Could it be that the assembly from which you configure your logger does not respect the `assemblyPrefix`? This was previously possible but is now removed. If you need to directly configure which assemblies are allowed, you can use the `allowedAssemblies` parameter instead. I have spotted an issue in 1.0.2 regarding this filtering of the calling assembly though, and have patched it in 1.0.3. Please try with that and ensure the above. Let me know if that doesn't work! :)

**Comment by raffsokolowski** [comment]
Hi Johannes,

I have tried 1.0.3 and it still doesn't work for me.
My logger is configured in Program.cs as below and my entire project uses the same assembly name, this all works fine with 1.0.1


namespace MyAssembly;

public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((hostingContext, config) => {})
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            })
            .UseSerilog((hostingContext, services, loggerConfiguration) => loggerConfiguration
                    .ReadFrom.Services(services)
                    .ReadFrom.Configuration(hostingContext.Configuration)
                    .Enrich.FromLogContext()
                    .Enrich.WithCallerInfo(includeFileInfo: false, assemblyPrefix: "MyAssembly.")
                    .Enrich.With(services.GetRequiredService<HttpContextEnricher>())
            );
}

**Comment by raffsokolowski** [comment]
I have managed to get it working using the allowedAssemblies instead of assemblyPrefix with 1.0.3

.Enrich.WithCallerInfo(includeFileInfo: false, allowedAssemblies: new List<string> { "MyAssembly" } )

**Comment by johannesmols** [comment]
Hi @raffsokolowski, good to hear. It's unfortunately quite hard for me to troubleshoot without a full example. Is your code by any chance open source? In my tests the assemblies are discovered just fine, so it's hard to say what's going wrong.

**Comment by raffsokolowski** [comment]
Unfortunately its not open source, not sure how I could help identify the issue, it seemed to work correctly in version 1.0.1

**Comment by johannesmols** [comment]
Hi @raffsokolowski, I just had another look at your code. Could it be that it isn't working because your assembly prefix is "MyAssembly." but your Program.cs is in "MyAssembly"? You have a dot in your argument, and the full assembly name is checked whether it starts with your prefix, which it doesn't when it's the root namespace like this.

I just released v1.0.4 thanks to a pull request that adds support for excluding certain prefixes and restricting the depth of the source file path. It has also slightly changed how assemblies are discovered again, hopefully covering more use cases. Could you try whether it works with this new version? And if it maybe is just that dot that's causing the issue :)
