### ISSUE TITLE
Always log the first assembly

### ISSUE THREAD

**Issue by kenny-reyes** [pm4net/serilog-enrichers-callerinfo#4]
NET 8 

The enricher can't log more than the initial Assembly

```
      {
        "Name": "WithCallerInfo",
        "Args": {
          "includeFileInfo": "true",
          "assemblyPrefix": "Company.",
          "startingAssembly": "Company.ApiHost"
        }
      }    
```

In EnricherConfiguration.cs GetAssemblies  line 89

`AssemblyExistsInList(asmNames, asm)`

 Always true

**Comment by johannesmols** [comment]
Hi @kenny-reyes, thanks for raising the issue. I tested and can see I made an error of checking the original assembly instead of the referenced one when deciding whether to include it. I fixed this and it is now available in v1.0.5. Could you check if that solves your issue?
